---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: document
  path: about/index.md
  label: About Paavan
- type: document
  path: _includes\_footer.njk
  label: Footer
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: drafts
  label: Drafts
  create: documents
  match: "**/*"
  templates:
  - blog-post
  - draft-blog-post
- type: directory
  path: posts
  label: Posts
  create: documents
  match: "*.md"
  templates:
  - blog-post
- type: heading
  label: Don't write to be read
- type: heading
  label: Write to write, explore, experiment, share, express, inspire
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: _site
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run serve
